version: '3.8'
services:
  db:
    # Runs the PostgreSQL database
    image: postgres
    environment:
      POSTGRES_DB: typescript_api
      POSTGRES_USER: typescript_user
      POSTGRES_PASSWORD: password
    expose:
      - '5432'
  # We should change web to api
  web:
    # Runs the API
    build: devU-api
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      db:
        condition: service_started
    # Comment selection:
    # The volumes of the config is mounted onto the config/tmp to prevent overwrites of the data once it is mounted.
    # This can be pervented using copyno option in volumes, sadly I'm too dumb to set it up
    # You can also not use volumes at all, just hard to keep files during build time from containers
    # Optional for local testing
    # volumes:
    #   - ./devU-api/config:/app/config/tmp
    ports:
      - '3001:3001'

  # Frontend Docker service
  # Builds the frontend of the applications
  # This includes the devU-client, Nginx
  client:
    build:
      context: devU-client
    # Hooking up the nginx config files are configs which can be directly mounted
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    # Same issue as above can be mount correctly using nocopy but need to amount into a alter folder, that the files was copy into after
    # the build stage was finish to prevent overwriting the folders during mounting
    # This will be optional, since it should only be used for local testing, most of the stuff should be done in docker
    # volumes:
    #   - ./dist/local:/dist/local:rw
    ports:
      - "9000:80"
  minio:
    image: minio/minio
    expose:
      - '9000'
    environment:
      MINIO_ROOT_USER: typescript_user
      MINIO_ROOT_PASSWORD: changeMe
    command: server /data --console-address ":9001"
# Definiting config files
configs:
  nginx_config:
    file: ./nginx.conf